name: Notify apt repo

on:
  push:
  workflow_dispatch:

env:
  DEST_USER: miatoll-linux
  DEST_REPO: repo

jobs:
  build:
    name: Notify
    runs-on: ubuntu-latest
    steps:
      - name: Send notification
        run: |
            curl -H "Authorization: token ${{ secrets.WEBHOOKS_SECRET }}" \
            -H 'Accept: application/vnd.github.everest-preview+json' \
            "https://api.github.com/repos/${{ env.DEST_USER }}/${{ env.DEST_REPO }}/dispatches" \
            -d '{"event_type": "update_repo", "client_payload": {"repository": "${{ github.repository }}"}}'
      - name: Clean old workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 1
